{% set version = "1.1.11" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 6924aee9300c803dbff0a330f0bc787388bc0435124e40aa9d06594949c5d6c6

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}     # [unix]
    - {{ native }}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
