{% set version = "1.56.0" %}
package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 05898e481a04b44d4eda575c7b585f26a1f19f5ac7ac06780371453332de4afb

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
