{% set version = "0.13.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 677854cc1b3a177f2281979008cebc1880b0149ebd7be5dc5c58d162ed1e5522

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{native}}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
