{% set version = "0.11.1" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 956991150e9beee6a560ece265cd5a79355f3556dfbb6a9864221bf2fabe41d5

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{native}}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
