{% set version = "0.11.9" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 61dcccf81d0bbd0bdfb2651136a2622b75514549f69e2f7f3d58b83acd73a549

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{native}}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
