{% set version = "1.21.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 8834d841d5129cc24ee59ffd97bee6f11d5145d2104bbf248f066ab5dafb7407

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}     # [unix]
    - {{ native }}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
