{% set version = "0.19.2" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 7d26392e1e70d382d20ef478a2dfa093c410f8db2d2689615c89cf3f69166063

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}     # [unix]
    - {{ native }}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
