{% set version = "1.32.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: broot
  version: {{ version }}

source:
  url: https://github.com/Canop/broot/archive/v{{ version }}.tar.gz
  sha256: 0b9bf4a0dfa8a9cdcefcf18222dba4025379a8fa19190075835a99a507ae3d73

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}     # [unix]
    - {{ native }}binutils      # [win]

test:
  commands:
    - broot --help

about:
  home: https://github.com/Canop/broot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Balanced tree view + fuzzy search + BFS + customizable launcher
  doc_url: https://dystroy.org/broot/

extra:
  recipe-maintainers:
    - dbast
